/**
 * Static interpretations for slow-planet house transits.
 * Keyed as `${planet}:${houseNumber}` — e.g. "Neptune:8".
 *
 * Each planet represents a core archetypal process that operates through whatever
 * house it transits. Jupiter expands, Saturn structures, Uranus disrupts, Neptune
 * dissolves, Pluto transforms. The house determines the life area where this
 * process unfolds.
 */

export interface TransitInterpretation {
  headline: string;
  overview: string;
  themes: string[];
  /** What this transit tends to open up or bring. */
  gifts: string[];
  /** What it can cost or demand. */
  challenges: string[];
  /** The core archetypal process: Expand, Structure, Disrupt, Dissolve, Transform. */
  coreProcess: "Expand" | "Structure" | "Disrupt" | "Dissolve" | "Transform";
  /** Approximate duration, chart-dependent. */
  typicalDuration: string;
}

type Key = string; // `${Planet}:${1..12}`

const DATA: Record<Key, TransitInterpretation> = {
  // ─── JUPITER: Expand ────────────────────────────────────────────────────────
  "Jupiter:1": {
    headline: "Expansion of Self",
    overview: "Jupiter moving through your first house brings optimism and a sense of personal possibility. You feel more confident, more visible. Opportunities seem to arrive naturally. The risk is overextending or assuming that luck will cover practical gaps.",
    themes: ["Identity", "Confidence", "Opportunity", "Optimism"],
    gifts: ["Increased presence and charisma", "Natural confidence in self-expression", "A sense that doors are opening"],
    challenges: ["Overconfidence or overextension", "Ego inflation", "Neglecting practical limits"],
    coreProcess: "Expand",
    typicalDuration: "~1 year (highly variable by chart)",
  },
  "Jupiter:2": {
    headline: "Growth in Resources",
    overview: "Jupiter in the second house tends to expand what you earn and what you value. Financial opportunity may open up, and self-worth feels buoyed. The risk is spending as fast as it arrives, or confusing material growth with spiritual worth.",
    themes: ["Finances", "Self-worth", "Security", "Values"],
    gifts: ["Income growth or new financial opportunity", "Renewed sense of personal value", "Generosity flowing both ways"],
    challenges: ["Overspending or financial over-confidence", "Neglecting discipline", "Temporary gains masking weakness"],
    coreProcess: "Expand",
    typicalDuration: "~1 year (highly variable by chart)",
  },
  "Jupiter:3": {
    headline: "Expanding the Mind",
    overview: "Communication, learning, and local connections all benefit. Ideas flow easily, and you feel natural in expressing them. Short journeys open unexpected doors. The risk is scatter — too many ideas, none followed through.",
    themes: ["Communication", "Learning", "Curiosity", "Local connection"],
    gifts: ["Easy, expansive communication", "Natural curiosity and learning appetite", "Successful writing or teaching"],
    challenges: ["Scattered mental energy", "Difficulty with depth or focus", "Over-promising"],
    coreProcess: "Expand",
    typicalDuration: "~1 year (highly variable by chart)",
  },
  "Jupiter:4": {
    headline: "Home and Family Open",
    overview: "The home and family sphere receives a blessing. You may welcome new people, find more space, or simply feel more settled. Inner emotional security deepens. The risk is taking on too much responsibility or material overcommitment.",
    themes: ["Home", "Family", "Roots", "Emotional security"],
    gifts: ["Improved domestic harmony", "Expanded sense of belonging", "Family opportunity"],
    challenges: ["Overextending family commitments", "Taking on too much financial obligation"],
    coreProcess: "Expand",
    typicalDuration: "~1 year (highly variable by chart)",
  },
  "Jupiter:5": {
    headline: "Creative and Romantic Expansion",
    overview: "Romance, creativity, children, and play all expand under this transit. Life feels lighter and more joyful. Creative projects attract luck and interest. Romantic connection is possible or deepens. The risk is overindulgence or chasing excitement without substance.",
    themes: ["Romance", "Creativity", "Joy", "Self-expression", "Play"],
    gifts: ["Creative recognition or breakthrough", "Romantic deepening or new connection", "Greater capacity for delight"],
    challenges: ["Romantic idealization", "Scattered creative energy", "Overindulgence"],
    coreProcess: "Expand",
    typicalDuration: "~1 year (highly variable by chart)",
  },
  "Jupiter:6": {
    headline: "Work and Routine Improve",
    overview: "Daily work becomes more satisfying, and you may gain recognition for skill or land a better role. Routine and health respond well to attention. The risk is overwork under a banner of enthusiasm, or neglecting recovery.",
    themes: ["Work", "Routine", "Health", "Service", "Mastery"],
    gifts: ["Career recognition or advancement", "Improved daily satisfaction", "Health responding positively to effort"],
    challenges: ["Overwork or burnout", "Neglecting rest", "Unrealistic productivity expectations"],
    coreProcess: "Expand",
    typicalDuration: "~1 year (highly variable by chart)",
  },
  "Jupiter:7": {
    headline: "Partnership Flourishing",
    overview: "One-on-one relationships improve and deepen. Partnerships of all kinds — romantic, business, legal — benefit from goodwill and mutual benefit. The risk is over-idealising a partner or overcommitting to too many simultaneous relationships.",
    themes: ["Partnership", "Commitment", "Cooperation", "Contracts"],
    gifts: ["New partnership or deepening of existing", "Improved cooperation", "Beneficial contractual outcomes"],
    challenges: ["Over-idealization of partners", "Overcommitting", "Glossing over incompatibilities"],
    coreProcess: "Expand",
    typicalDuration: "~1 year (highly variable by chart)",
  },
  "Jupiter:8": {
    headline: "Shared Gains and Transformation",
    overview: "Shared resources, intimacy, and psychological depth all become sites of growth. Joint finances may improve. Psychologically, you gain access to material you were previously unable to face. The risk is financial entanglement or using depth-work as avoidance.",
    themes: ["Shared resources", "Transformation", "Intimacy", "Psychology"],
    gifts: ["Financial gain through shared ventures or inheritance", "Psychological breakthrough", "Greater intimacy", "Access to depths"],
    challenges: ["Financial entanglement", "Overconfidence in risky ventures", "Intensity without integration"],
    coreProcess: "Expand",
    typicalDuration: "~1 year (highly variable by chart)",
  },
  "Jupiter:9": {
    headline: "Wisdom and Horizons Expand",
    overview: "Jupiter is at home here. Philosophy, travel, higher education, and spiritual inquiry all expand naturally. You are drawn toward meaning-making. The risk is dogmatism — certainty replacing curiosity — or perpetual restlessness.",
    themes: ["Philosophy", "Travel", "Higher learning", "Spirituality", "Meaning"],
    gifts: ["Broadened understanding", "Successful study or teaching", "Travel as expansion", "Spiritual insight"],
    challenges: ["Dogmatism or certainty", "Perpetual seeking without settling", "Restlessness"],
    coreProcess: "Expand",
    typicalDuration: "~1 year (highly variable by chart)",
  },
  "Jupiter:10": {
    headline: "Career and Status Rise",
    overview: "Public recognition and professional advancement are strongly supported. You may step into leadership or gain visibility. Your reputation expands favorably. The risk is overreach or building reputation on an unstable foundation.",
    themes: ["Career", "Status", "Authority", "Achievement", "Public life"],
    gifts: ["Career advancement or recognition", "Increased public visibility", "Authority and leadership"],
    challenges: ["Overreach beyond competence", "Reputation inflation without substance", "Unsustainable responsibility"],
    coreProcess: "Expand",
    typicalDuration: "~1 year (highly variable by chart)",
  },
  "Jupiter:11": {
    headline: "Networks and Community Grow",
    overview: "Your social world expands. New friendships, group affiliations, and collaborative projects multiply. Goals gain traction through community support. The risk is spreading thin or idealism about what groups can deliver.",
    themes: ["Friendship", "Groups", "Goals", "Community", "Collective"],
    gifts: ["Influential new connections", "Group projects succeeding", "Goals becoming achievable"],
    challenges: ["Spreading too thin", "Idealism about groups", "Overcommitment"],
    coreProcess: "Expand",
    typicalDuration: "~1 year (highly variable by chart)",
  },
  "Jupiter:12": {
    headline: "Inner Expansion",
    overview: "Growth happens inwardly — in spiritual practice, solitude, and psychological work. What is released here clears the way for the Jupiter-1 rebirth to follow. The risk is escapism or growth that remains invisible.",
    themes: ["Spirituality", "Solitude", "Healing", "Retreat", "Karma"],
    gifts: ["Profound spiritual opening", "Deep healing work", "Compassion deepening", "Karmic clarity"],
    challenges: ["Escapism or avoidance", "Unseen growth going unvalidated", "Isolation"],
    coreProcess: "Expand",
    typicalDuration: "~1 year (highly variable by chart)",
  },

  // ─── SATURN: Structure ──────────────────────────────────────────────────────
  "Saturn:1": {
    headline: "Identity Consolidates",
    overview: "Saturn crossing the ascendant marks a significant chapter: you are asked to take full responsibility for who you are. It can feel heavy — the world seems less forgiving, your energy more limited. But what is built here lasts. This is the beginning of a new authentic identity.",
    themes: ["Identity", "Responsibility", "Discipline", "Maturity"],
    gifts: ["Hard-won self-knowledge", "Authentic identity, stripped of pretence", "Real discipline bearing fruit"],
    challenges: ["Low energy or self-doubt", "Feeling the weight of responsibility", "Identity uncertainty before consolidation"],
    coreProcess: "Structure",
    typicalDuration: "2–3 years (highly variable by chart)",
  },
  "Saturn:2": {
    headline: "Resources Tested and Secured",
    overview: "Finances and values are put under pressure. What you earn may feel insufficient; what you own may be questioned. The lesson is building real financial security and authentic values, not their appearance.",
    themes: ["Finances", "Security", "Values", "Discipline"],
    gifts: ["Sound financial habits established for life", "Clarity about what holds real value", "Debt reduced or structures solidified"],
    challenges: ["Financial pressure or tightness", "Self-worth being tested", "Fear about material security"],
    coreProcess: "Structure",
    typicalDuration: "2–3 years (highly variable by chart)",
  },
  "Saturn:3": {
    headline: "Thinking Becomes Deliberate",
    overview: "Communication and thinking become more careful and exacting. You speak less but mean more. Study that requires real discipline rewards you. Nearby relationships may bring practical demands.",
    themes: ["Communication", "Study", "Precision", "Discipline"],
    gifts: ["Deep, rigorous thinking", "Weightier communication and writing", "Completion of demanding intellectual work"],
    challenges: ["Mental heaviness", "Strained local relationships", "Communication feeling effortful"],
    coreProcess: "Structure",
    typicalDuration: "2–3 years (highly variable by chart)",
  },
  "Saturn:4": {
    headline: "Foundation Work: Home and Family",
    overview: "Home, family, and emotional roots are tested and restructured. Old family patterns become undeniable. Major changes in family roles or living situations are common. You are learning to build emotional foundations on solid ground.",
    themes: ["Home", "Family", "Roots", "Emotional security"],
    gifts: ["Family patterns finally understood and addressed", "A home life built on solid ground", "Emotional maturity through difficulty"],
    challenges: ["Domestic change or upheaval", "Family responsibility or burden", "Feeling isolated or unsupported"],
    coreProcess: "Structure",
    typicalDuration: "2–3 years (highly variable by chart)",
  },
  "Saturn:5": {
    headline: "Earning Your Joy",
    overview: "Creativity and pleasure do not come easily now — they require work and commitment. Creative projects that survive this transit are the real ones. Romance is serious rather than light. The demand is depth and authenticity.",
    themes: ["Creativity", "Discipline", "Romance", "Commitment"],
    gifts: ["Creative work of lasting quality", "A relationship built on substance", "The discipline to finish what you start"],
    challenges: ["Fun feeling blocked or effortful", "Creative blocks", "Romance feeling like obligation"],
    coreProcess: "Structure",
    typicalDuration: "2–3 years (highly variable by chart)",
  },
  "Saturn:6": {
    headline: "The Long Work: Mastery Through Routine",
    overview: "Work and health demand sustained attention. This is the transit of grinding, daily practice — but what you build now becomes the bedrock of your competence. Demands around routine, habit, and self-discipline come to the foreground.",
    themes: ["Work", "Health", "Routine", "Mastery", "Service"],
    gifts: ["Mastery of a craft through practice", "Health habits that truly transform", "Professional reputation for reliability"],
    challenges: ["Workload feeling unsustainable", "Health demanding attention and structure", "Difficulty maintaining motivation"],
    coreProcess: "Structure",
    typicalDuration: "2–3 years (highly variable by chart)",
  },
  "Saturn:7": {
    headline: "Relationships Under Scrutiny",
    overview: "Partnerships — romantic and professional — are tested for real substance. Those that survive become pillars. Those that dissolve were already hollow. This is a transit of commitment or honest endings. Authentic relating becomes non-negotiable.",
    themes: ["Partnership", "Commitment", "Authenticity", "Honesty"],
    gifts: ["A relationship deepened by shared difficulty", "Clarity about what you actually need", "Partnerships built to last"],
    challenges: ["Relationship strain or significant change", "Feeling alone within a partnership", "Legal or contractual difficulties"],
    coreProcess: "Structure",
    typicalDuration: "2–3 years (highly variable by chart)",
  },
  "Saturn:8": {
    headline: "Facing Depths: Power and Debt",
    overview: "Shared finances, joint assets, and psychological depth all require careful attention. Debts are addressed — financial and psychological. Power dynamics in relationships become undeniable and must be renegotiated. This is about facing what is real, not what is comfortable.",
    themes: ["Shared resources", "Debt", "Power dynamics", "Depth", "Transformation"],
    gifts: ["Old debts cleared (financial and psychological)", "Psychological maturation", "Mastery over fear"],
    challenges: ["Financial strain from shared obligations", "Power struggles", "Confronting what is unwelcome"],
    coreProcess: "Structure",
    typicalDuration: "2–3 years (highly variable by chart)",
  },
  "Saturn:9": {
    headline: "Testing Your Beliefs",
    overview: "Philosophy, faith, and worldview are put under scrutiny. Beliefs that cannot withstand examination fall away. Formal study becomes demanding but rewarding. Travel may be limited or purposeful rather than expansive. You are building a mature worldview.",
    themes: ["Philosophy", "Belief", "Higher learning", "Faith", "Meaning"],
    gifts: ["A worldview tempered by experience", "Academic rigor producing real credentials", "Mature spiritual understanding"],
    challenges: ["Disillusionment with beliefs", "Rigid thinking replacing inquiry", "Difficulty with foreign or unfamiliar"],
    coreProcess: "Structure",
    typicalDuration: "2–3 years (highly variable by chart)",
  },
  "Saturn:10": {
    headline: "Career Peak: Authority and Responsibility",
    overview: "Saturn in the tenth house is often the most professionally significant transit. Status is tested, and if foundations are sound, you rise to real authority. If not, the structure cracks and must be rebuilt. This is the transit of earned power.",
    themes: ["Career", "Authority", "Status", "Legacy", "Responsibility"],
    gifts: ["Career peak and real authority", "Long-term professional legacy", "Respect earned through sustained effort"],
    challenges: ["Professional scrutiny or failure", "The weight of responsibility", "Burnout"],
    coreProcess: "Structure",
    typicalDuration: "2–3 years (highly variable by chart)",
  },
  "Saturn:11": {
    headline: "Community Redefined: Real Over Ideal",
    overview: "Friendships and group affiliations are tested. Some prove hollow and end. Goals are examined seriously — which are real, which were fantasies? Community becomes smaller but genuinely supportive. You are learning about authentic belonging.",
    themes: ["Friendship", "Groups", "Goals", "Community", "Vision"],
    gifts: ["Lifelong friendships proven under pressure", "Realistic, achievable long-term goals", "Genuinely supportive community"],
    challenges: ["Social isolation or group exclusion", "Disillusionment with ideals", "Goals feeling impossible"],
    coreProcess: "Structure",
    typicalDuration: "2–3 years (highly variable by chart)",
  },
  "Saturn:12": {
    headline: "The Inner Reckoning",
    overview: "The final Saturn transit. Old patterns, fears, and unresolved material surface for examination. This is a period of solitude, psychological honesty, and spiritual work before the Saturn-1 cycle begins. You are clearing debris for what comes next.",
    themes: ["Solitude", "Karma", "Spirituality", "Shadow", "Endings"],
    gifts: ["Deep healing of unconscious patterns", "Spiritual maturity", "Release of what has been carried"],
    challenges: ["Isolation and heaviness", "Encounters with the shadow", "Exhaustion"],
    coreProcess: "Structure",
    typicalDuration: "2–3 years (highly variable by chart)",
  },

  // ─── URANUS: Disrupt ────────────────────────────────────────────────────────
  "Uranus:1": {
    headline: "Radical Reinvention",
    overview: "Uranus crossing the ascendant is one of the most liberating and disruptive transits. Who you thought you were gets shaken loose. The urge for freedom and authenticity becomes irresistible — you reinvent yourself, often suddenly. This is about becoming genuinely yourself.",
    themes: ["Freedom", "Reinvention", "Authenticity", "Awakening"],
    gifts: ["Completely renewed sense of self", "Freedom from outgrown roles", "Electric energy and originality"],
    challenges: ["Destabilising impulsiveness", "Becoming unpredictable or erratic to others", "Difficulty sustaining routine"],
    coreProcess: "Disrupt",
    typicalDuration: "~7 years (highly variable by chart)",
  },
  "Uranus:2": {
    headline: "Financial Disruption and Liberation",
    overview: "Income, possessions, and values all undergo sudden, unexpected change. Financial ups and downs are sharp. The liberation is discovering that security comes from adaptability, not accumulation. You are learning a new relationship to resources.",
    themes: ["Finances", "Values", "Security", "Freedom", "Attachment"],
    gifts: ["Financial breakthroughs through unconventional means", "Freedom from material attachment", "Discovery of non-material security"],
    challenges: ["Financial instability", "Unpredictable income", "Values upended without clear replacement"],
    coreProcess: "Disrupt",
    typicalDuration: "~7 years (highly variable by chart)",
  },
  "Uranus:3": {
    headline: "Mind Electrified: New Ideas and Connections",
    overview: "Thinking, communication, and information all accelerate. You may be drawn to entirely new fields of inquiry. Technology and media often play a role. Local relationships bring sudden changes. Your mind is being liberated into new territory.",
    themes: ["Innovation", "Communication", "Ideas", "Technology", "Freedom"],
    gifts: ["Flashes of genuine insight", "Non-linear intellectual life", "Exciting unexpected connections"],
    challenges: ["Restlessness and lack of follow-through", "Erratic communication", "Disrupted local relationships"],
    coreProcess: "Disrupt",
    typicalDuration: "~7 years (highly variable by chart)",
  },
  "Uranus:4": {
    headline: "Uprooting: Home and Family Disrupted",
    overview: "The foundation shifts. Home life, family structures, and sense of belonging undergo sudden, often involuntary change. This can mean literal relocations or family upheavals. You are learning a new definition of home and rootedness.",
    themes: ["Home", "Roots", "Family", "Belonging", "Change"],
    gifts: ["Freedom from domestic arrangements that were constraining", "A new relationship to home and belonging", "Family patterns finally broken"],
    challenges: ["Involuntary moves or housing instability", "Family relationships strained", "Feeling unmoored or unbelonging"],
    coreProcess: "Disrupt",
    typicalDuration: "~7 years (highly variable by chart)",
  },
  "Uranus:5": {
    headline: "Creative Revolution",
    overview: "Creative expression breaks free from all previous constraints. New artistic directions and unconventional attractions emerge. Self-expression becomes radically authentic. The risk is that liberation can look like recklessness to those around you.",
    themes: ["Creativity", "Romance", "Freedom", "Originality", "Expression"],
    gifts: ["Genuinely original creative work", "Electrifying romantic renewal", "Freedom to create outside expectation"],
    challenges: ["Unstable romantic dynamics", "Scattered creative output", "Recklessness"],
    coreProcess: "Disrupt",
    typicalDuration: "~7 years (highly variable by chart)",
  },
  "Uranus:6": {
    headline: "Disrupting Work and Routine",
    overview: "Work conditions, daily habits, and routines all undergo sudden, unexpected change. The old ways no longer work. New methods — often technological — emerge. You are being liberated into a new way of working and being in your body.",
    themes: ["Work", "Routine", "Health", "Innovation", "Liberation"],
    gifts: ["Breakthrough work methods or environment", "New health approaches", "Freedom from oppressive routine"],
    challenges: ["Job instability or disruption", "Unpredictable energy levels", "Difficulty maintaining consistent structure"],
    coreProcess: "Disrupt",
    typicalDuration: "~7 years (highly variable by chart)",
  },
  "Uranus:7": {
    headline: "Partnership Shock and Reinvention",
    overview: "Relationships are the theatre for Uranus's revolution. Existing partnerships may suddenly change shape, end, or be reinvented in unconventional ways. The demand is authentic, equal relating — no more roles or expectations. Attract or become electrifyingly alive within connection.",
    themes: ["Partnership", "Freedom", "Equality", "Authenticity"],
    gifts: ["A completely new model of relationship", "Liberation from constraint", "Electrifying new connections"],
    challenges: ["Sudden partnership endings", "Attracting unpredictable partners", "Commitment feeling at odds with freedom"],
    coreProcess: "Disrupt",
    typicalDuration: "~7 years (highly variable by chart)",
  },
  "Uranus:8": {
    headline: "Deep Transformation, Suddenly",
    overview: "Shared finances, power dynamics, and psychological depths all undergo abrupt, startling change. Inheritances or financial entanglements may appear or dissolve unexpectedly. Psychologically, what was buried erupts. You are being liberated from compulsions and patterns.",
    themes: ["Transformation", "Shared resources", "Power", "Sudden change", "Psychology"],
    gifts: ["Psychological breakthroughs", "Unexpected financial resolution", "Freedom from compulsion"],
    challenges: ["Sudden financial upheaval", "Shocking relationship revelations", "Psychological instability as material surfaces"],
    coreProcess: "Disrupt",
    typicalDuration: "~7 years (highly variable by chart)",
  },
  "Uranus:9": {
    headline: "Philosophical Awakening",
    overview: "Philosophy, belief systems, travel, and higher learning all become sites of sudden liberation. Old belief systems shatter; new, expanded ones emerge. Long-distance travel or encounters with radically different cultures are likely. Your worldview is being revolutionized.",
    themes: ["Philosophy", "Belief", "Travel", "Learning", "Expansion"],
    gifts: ["Genuinely liberated worldview", "Exciting encounters with different ideas", "Spiritual or intellectual breakthrough"],
    challenges: ["Discarding beliefs too quickly", "Restless, rootless searching", "Disrupted plans"],
    coreProcess: "Disrupt",
    typicalDuration: "~7 years (highly variable by chart)",
  },
  "Uranus:10": {
    headline: "Career Upheaval: Authenticity Rises",
    overview: "Professional life and public image are disrupted, often dramatically. A stable career path may suddenly end; an unexpected one opens. The demand is to do work that is genuinely yours. You are being freed into authentic vocation.",
    themes: ["Career", "Status", "Authenticity", "Innovation"],
    gifts: ["A career path finally genuinely original", "Public recognition for unconventional contribution", "Freedom from status anxiety"],
    challenges: ["Sudden job loss or disruption", "Public image shifting outside your control", "Difficulty sustaining conventional paths"],
    coreProcess: "Disrupt",
    typicalDuration: "~7 years (highly variable by chart)",
  },
  "Uranus:11": {
    headline: "Group and Network Revolution",
    overview: "Social networks, group affiliations, and long-held goals all shift dramatically. Old friend groups may scatter; new, more aligned communities appear. Goals that were inherited or imposed fall away. You are finding your authentic tribe and true direction.",
    themes: ["Friendship", "Community", "Goals", "Collective", "Freedom"],
    gifts: ["A social world full of genuinely interesting people", "Long-held goals replaced by authentic ones", "Group projects that push boundaries"],
    challenges: ["Sudden friendship or group endings", "Community instability", "Goals dissolving faster than new ones cohere"],
    coreProcess: "Disrupt",
    typicalDuration: "~7 years (highly variable by chart)",
  },
  "Uranus:12": {
    headline: "Inner Liberation: Unconscious Awakening",
    overview: "The unconscious is where Uranus works in the twelfth house — sudden, surprising insights emerging from depths. Spiritual awakening, vivid dreams, and unexpected healing are all possible. Old karmic patterns crack open. You are being liberated on the deepest level.",
    themes: ["Spirituality", "Unconscious", "Liberation", "Healing", "Awakening"],
    gifts: ["Sudden spiritual breakthrough", "Rapid healing of deep patterns", "A lighter relationship with the unconscious"],
    challenges: ["Disrupted sleep or vivid dreams", "Anxiety from material surfacing", "Difficulty grounding insights"],
    coreProcess: "Disrupt",
    typicalDuration: "~7 years (highly variable by chart)",
  },

  // ─── NEPTUNE: Dissolve ──────────────────────────────────────────────────────
  "Neptune:1": {
    headline: "Dissolving the Ego",
    overview: "Neptune crossing the ascendant blurs the edges of identity. You may feel you are losing yourself — or discovering a more porous, compassionate version. Artistic sensitivity and spiritual attunement heighten; so does susceptibility to others' influence. You are learning a more permeable self.",
    themes: ["Identity", "Spirituality", "Compassion", "Dissolution", "Sensitivity"],
    gifts: ["Deep artistic and spiritual sensitivity", "Compassion extending to all", "Release of ego rigidity"],
    challenges: ["Identity confusion", "Susceptibility to influence", "Difficulty with boundaries"],
    coreProcess: "Dissolve",
    typicalDuration: "~13 years (highly variable by chart)",
  },
  "Neptune:2": {
    headline: "Dissolving Material Attachments",
    overview: "Money and material security become slippery. What you earn may be unclear; what you own may lose its hold on you. The invitation is to find a richer sense of value beyond the material. The risk is financial negligence or illusion.",
    themes: ["Finances", "Values", "Materialism", "Spirituality"],
    gifts: ["Freedom from purely material security", "Inspired earning through creative or spiritual work", "A more fluid relationship with money"],
    challenges: ["Financial confusion or loss", "Unclear income", "Difficulty holding onto resources"],
    coreProcess: "Dissolve",
    typicalDuration: "~13 years (highly variable by chart)",
  },
  "Neptune:3": {
    headline: "The Poetic Mind",
    overview: "Thinking becomes more intuitive and less logical. Language takes on symbolic weight; you are drawn to poetry, music, and imagery. But precision can suffer, and information may arrive distorted. You are learning to think in symbols and dreams.",
    themes: ["Communication", "Intuition", "Poetry", "Imagination", "Learning"],
    gifts: ["Extraordinary poetic and creative expression", "Heightened intuition and sensitivity", "Learning through symbol and story"],
    challenges: ["Difficulty with precise, logical thinking", "Misinformation or misunderstanding", "Scattered mental energy"],
    coreProcess: "Dissolve",
    typicalDuration: "~13 years (highly variable by chart)",
  },
  "Neptune:4": {
    headline: "Dissolving Family Foundations",
    overview: "Home, family, and emotional roots become suffused with Neptune's fog. Old family patterns dissolve — sometimes gently, sometimes through significant change. You may feel unmoored, but a deeper, more spiritual sense of home can emerge. Family boundaries become permeable.",
    themes: ["Home", "Family", "Roots", "Belonging", "Spirituality"],
    gifts: ["Spiritual relationship to home and belonging", "Healing of family patterns", "Home saturated with beauty and peace"],
    challenges: ["Home life feeling unstable", "Family relationships becoming unclear", "Loss or change in domestic sphere"],
    coreProcess: "Dissolve",
    typicalDuration: "~13 years (highly variable by chart)",
  },
  "Neptune:5": {
    headline: "Creative Transcendence",
    overview: "Creativity becomes a spiritual act. Art, music, and imagination flow from a deeper source. Romantic life is colored by idealism and longing. The risk is projection — seeing what you want rather than what is there.",
    themes: ["Creativity", "Romance", "Imagination", "Idealism", "Spirituality"],
    gifts: ["Transcendent creative expression", "Deeply romantic, soulful connection", "Creativity as spiritual practice"],
    challenges: ["Romantic idealization and disillusionment", "Creative work dissolving before completion", "Blurred reality"],
    coreProcess: "Dissolve",
    typicalDuration: "~13 years (highly variable by chart)",
  },
  "Neptune:6": {
    headline: "Service and Dissolution of Routine",
    overview: "Work and health are infused with Neptune's sensitivity. You may be drawn to healing professions, spiritual service, or creative work. Health symptoms can be elusive — difficult to diagnose, energy levels fluctuating. You are learning a new relationship to work and body.",
    themes: ["Service", "Health", "Healing", "Work", "Spirituality"],
    gifts: ["Work as spiritual vocation", "Profound capacity for healing", "Daily life imbued with meaning"],
    challenges: ["Persistent fatigue or mysterious symptoms", "Confusion at work or poor boundaries", "Difficulty maintaining clear routine"],
    coreProcess: "Dissolve",
    typicalDuration: "~13 years (highly variable by chart)",
  },
  "Neptune:7": {
    headline: "The Idealized Partnership",
    overview: "Partnerships are idealized and spiritualized. You may encounter someone who feels like a soulmate — or discover that what felt like a soulmate was a projection. Boundaries become porous. The work is discerning real connection from fantasy.",
    themes: ["Partnership", "Idealization", "Soul connection", "Projection", "Boundaries"],
    gifts: ["A genuinely transcendent partnership", "Compassion and forgiveness in relating", "Psychic connection"],
    challenges: ["Deception or self-deception", "Idealization and disillusionment", "Difficulty seeing a partner clearly"],
    coreProcess: "Dissolve",
    typicalDuration: "~13 years (highly variable by chart)",
  },
  "Neptune:8": {
    headline: "Depths Without Bottom: Spiritual Transformation",
    overview: "Neptune in the eighth house is one of the most psychologically and spiritually penetrating transits. The veils between conscious and unconscious thin dramatically. Shared finances may be unclear or dissolve; intimate relationships carry mystical quality. You are learning to live with mystery.",
    themes: ["Transformation", "Spirituality", "Shared resources", "Mystery", "Depth"],
    gifts: ["Profound mystical and spiritual experience", "Psychic sensitivity at its peak", "Deep compassion for human mortality", "Healing of deep psychological wounds"],
    challenges: ["Financial confusion through shared accounts", "Difficulty separating your material from others'", "Boundaries between self and other dissolving"],
    coreProcess: "Dissolve",
    typicalDuration: "~13 years (highly variable by chart)",
  },
  "Neptune:9": {
    headline: "Spiritual Seeking and Idealism",
    overview: "Philosophy, spirituality, and higher learning are saturated with Neptune's longing for the infinite. You may be drawn deeply into a spiritual path or mystical study. The risk is spiritual bypassing or following a teacher who turns out to be illusory.",
    themes: ["Spirituality", "Philosophy", "Higher learning", "Faith", "Idealism"],
    gifts: ["A profoundly meaningful spiritual life", "Inspired teaching or writing", "Travel that opens doors to the numinous"],
    challenges: ["Disillusionment with spiritual teachers", "Beautiful beliefs untethered to reality", "Difficulty with structured learning"],
    coreProcess: "Dissolve",
    typicalDuration: "~13 years (highly variable by chart)",
  },
  "Neptune:10": {
    headline: "Career in Fog: Finding Your Calling",
    overview: "Public identity and career direction become unclear. You may feel unsure of what you are doing or why. Confusion in professional life is common. But when this clears, the work that remains is often genuinely soulful and vocation-driven.",
    themes: ["Career", "Vocation", "Public identity", "Confusion", "Purpose"],
    gifts: ["Work as genuine spiritual calling", "Public recognition for compassionate contribution", "Letting go of status that was never yours"],
    challenges: ["Career confusion or lack of direction", "Reputation difficult to control", "Professional scandal or deception"],
    coreProcess: "Dissolve",
    typicalDuration: "~13 years (highly variable by chart)",
  },
  "Neptune:11": {
    headline: "The Inspired Collective",
    overview: "Social idealism runs high. You may be drawn to collective or humanitarian causes, spiritual communities, or groups united by shared vision. But the vision can prove illusory, and disillusionment with groups often follows. Learning to distinguish inspiration from illusion.",
    themes: ["Community", "Idealism", "Collective", "Friendship", "Vision"],
    gifts: ["Involvement with inspired collective work", "Deep friendships of spiritual depth", "A vision of human possibility"],
    challenges: ["Idealization of groups, then disillusionment", "Friends who are hard to see clearly", "Collective dreams that dissolve"],
    coreProcess: "Dissolve",
    typicalDuration: "~13 years (highly variable by chart)",
  },
  "Neptune:12": {
    headline: "Home in the Infinite",
    overview: "Neptune in its natural house. The boundary between individual and universal thins nearly to invisibility. Mystical experience, compassion, and the dissolution of ego are available. So is boundless confusion and escapism. You are dissolving into the larger whole.",
    themes: ["Spirituality", "Mysticism", "Solitude", "Dissolution", "Transcendence"],
    gifts: ["Profound mystical union", "Compassion extending to all existence", "Release of deep unconscious material"],
    challenges: ["Psychological confusion and sensitivity", "Escapism through substances or fantasy", "Difficulty functioning in the ordinary world"],
    coreProcess: "Dissolve",
    typicalDuration: "~13 years (highly variable by chart)",
  },

  // ─── PLUTO: Transform ───────────────────────────────────────────────────────
  "Pluto:1": {
    headline: "Total Rebirth",
    overview: "Pluto crossing the ascendant is a once-in-a-lifetime transit for most people. The person who existed before is not the person who emerges. Power, will, and authentic self-expression are transformed at the deepest level. This is a complete shedding of skin.",
    themes: ["Identity", "Power", "Transformation", "Rebirth", "Authenticity"],
    gifts: ["A completely new, more powerful identity", "Access to depths of will previously unavailable", "Only what is real survives"],
    challenges: ["The death of the previous self", "Power struggles with those who preferred the old you", "Overwhelming intensity"],
    coreProcess: "Transform",
    typicalDuration: "12–20 years (highly variable by chart)",
  },
  "Pluto:2": {
    headline: "Wealth and Worth Transformed",
    overview: "What you earn, own, and value undergoes irreversible transformation. Financial structures may collapse entirely before being rebuilt. The deeper work is transformation of self-worth — from conditional to unassailable. You are learning what is truly valuable.",
    themes: ["Finances", "Self-worth", "Power", "Transformation", "Values"],
    gifts: ["A completely rebuilt relationship with money", "Self-worth no longer dependent on external validation", "Financial power through understanding depth"],
    challenges: ["Financial upheaval", "Obsession with resources or power", "Deep survival fears surfacing"],
    coreProcess: "Transform",
    typicalDuration: "12–20 years (highly variable by chart)",
  },
  "Pluto:3": {
    headline: "Words as Power: Communication Transformed",
    overview: "Thinking and communication become instruments of transformation. What you say carries more weight than before. The superficial falls away; you want only depth, honesty, and precision. Local relationships are sites of profound change.",
    themes: ["Communication", "Power of language", "Depth", "Truth", "Intensity"],
    gifts: ["Communication that genuinely changes minds", "A penetrating, incisive intellect", "Research and investigation at highest level"],
    challenges: ["Obsessive or intense thinking", "Compulsive speech that destroys relationships", "Sibling or local confrontation"],
    coreProcess: "Transform",
    typicalDuration: "12–20 years (highly variable by chart)",
  },
  "Pluto:4": {
    headline: "Roots Broken Open: Ancestral Patterns",
    overview: "Family, home, and emotional foundations are transformed at the deepest level. Old ancestral patterns — sometimes generations old — surface to be faced and cleared. Major changes in family roles or living situations are common. You are breaking generational cycles.",
    themes: ["Home", "Family", "Ancestry", "Foundations", "Shadow"],
    gifts: ["Breaking of generational patterns", "A completely new emotional foundation", "Understanding of the family shadow"],
    challenges: ["Family upheaval or estrangement", "Compulsive domestic patterns surfacing", "The full weight of inherited material"],
    coreProcess: "Transform",
    typicalDuration: "12–20 years (highly variable by chart)",
  },
  "Pluto:5": {
    headline: "Creative and Sexual Power",
    overview: "Creativity, sexuality, and self-expression are all transformed. The desire to create something meaningful — something that lasts — becomes all-consuming. Romantic relationships carry intense, fated qualities. What is created now comes from the deepest place.",
    themes: ["Creativity", "Sexuality", "Power", "Self-expression", "Passion"],
    gifts: ["Creative work of lasting power and depth", "Sexual and romantic transformation", "The full expression of creative power"],
    challenges: ["Obsessive or controlling dynamics", "Compulsive creativity at relationship's expense", "Power struggles around children"],
    coreProcess: "Transform",
    typicalDuration: "12–20 years (highly variable by chart)",
  },
  "Pluto:6": {
    headline: "Work and Health Transformed: Deepening Capacity",
    overview: "Daily life, work, and your relationship to health are all subject to Pluto's thorough transformation. Work environments may be sites of power struggles; your relationship to routine and body demands deep, structural attention. You are transforming your capacity for mastery.",
    themes: ["Work", "Health", "Power", "Mastery", "Transformation"],
    gifts: ["Work of genuine depth and transformative impact", "Health rebuilt from the ground up", "Mastery of complex, demanding fields"],
    challenges: ["Toxic work environments or power struggles", "Compulsive work habits", "Deep health work being required"],
    coreProcess: "Transform",
    typicalDuration: "12–20 years (highly variable by chart)",
  },
  "Pluto:7": {
    headline: "Partnership at the Edge: Complete Honesty",
    overview: "One-on-one relationships are the arena for Pluto's most intense work. Power dynamics, control, and what you bring to another person are all laid bare. Relationships either transform profoundly or end. There is no comfortable middle ground. You are learning authentic power in partnership.",
    themes: ["Partnership", "Power", "Intimacy", "Transformation", "Honesty"],
    gifts: ["A partnership that has been tested and is unbreakable", "Complete honesty about what you need", "Freedom from codependence"],
    challenges: ["Power struggles or control dynamics", "Relationship endings that feel like death", "Attracting intense, transformative partners"],
    coreProcess: "Transform",
    typicalDuration: "12–20 years (highly variable by chart)",
  },
  "Pluto:8": {
    headline: "Into the Underworld: Complete Regeneration",
    overview: "Pluto in its own house is at maximum power. Transformation, death, rebirth, shared resources, sexuality, and the occult are all intensified beyond comfort. What dies here is real. What is reborn is unrecognizable. This is the most complete transformation available.",
    themes: ["Transformation", "Death and rebirth", "Power", "Shared resources", "Occult"],
    gifts: ["Complete psychological regeneration", "Access to power never previously available", "Mastery of shared resources and financial depth"],
    challenges: ["Confronting death and mortality", "Overwhelming intensity in intimacy", "Obsession, compulsion, power addiction surfacing"],
    coreProcess: "Transform",
    typicalDuration: "12–20 years (highly variable by chart)",
  },
  "Pluto:9": {
    headline: "The Death of Belief: Wisdom Earned",
    overview: "Philosophy, religion, and worldview are stripped to the bone and rebuilt. Whatever you believed before, Pluto will test it until only what is genuinely true survives. This is the transit of existential reckoning — and of wisdom earned through fire.",
    themes: ["Philosophy", "Belief", "Higher learning", "Power and truth", "Depth"],
    gifts: ["A worldview forged through existential confrontation", "Teaching or writing that carries power", "Spiritual understanding from facing the abyss"],
    challenges: ["Loss of all previously held beliefs", "Fanaticism or compulsive belief-imposition", "Confrontation with institutions"],
    coreProcess: "Transform",
    typicalDuration: "12–20 years (highly variable by chart)",
  },
  "Pluto:10": {
    headline: "Power and Authority: Real vs. Apparent",
    overview: "Career, status, and public life are subject to Pluto's complete overhaul. Power may be accumulated — or stripped away. Either way, who you are in public is transformed beyond recognition. Work that survives is the work of genuine power.",
    themes: ["Career", "Authority", "Power", "Reputation", "Transformation"],
    gifts: ["Real authority and power in public life", "Career rebuilt on an entirely authentic foundation", "Public work of lasting transformative impact"],
    challenges: ["Public power struggles", "Career destruction before reconstruction", "The weight of genuine power"],
    coreProcess: "Transform",
    typicalDuration: "12–20 years (highly variable by chart)",
  },
  "Pluto:11": {
    headline: "Group Power and True Vision",
    overview: "Social networks, collective projects, and long-held goals all undergo irreversible transformation. The groups you belong to change profoundly — you may become a transformative force within them, or leave them behind. Goals are rebuilt around authentic power and purpose.",
    themes: ["Community", "Power", "Collective transformation", "Goals", "Vision"],
    gifts: ["A transformative presence in collective work", "Long-term goals rebuilt around authentic purpose", "Networks carrying real depth and influence"],
    challenges: ["Power struggles within groups", "Collective projects transformed beyond recognition", "Isolation as you outgrow old networks"],
    coreProcess: "Transform",
    typicalDuration: "12–20 years (highly variable by chart)",
  },
  "Pluto:12": {
    headline: "The Final Dissolution: Shadow Integration",
    overview: "Pluto in the twelfth house works in the deepest underground of the psyche. Unconscious material, karmic patterns, and the hidden shadow of the personality all surface to be transformed. This transit often precedes a complete rebirth — the Pluto-1 cycle to follow.",
    themes: ["Unconscious", "Shadow", "Karma", "Transformation", "Depth"],
    gifts: ["The most complete psychological transformation available", "Release of inherited and personal karmic material", "A completely clean slate"],
    challenges: ["Encounters with the darkest material in the psyche", "Extreme isolation", "Psychological crises resisting ordinary approaches"],
    coreProcess: "Transform",
    typicalDuration: "12–20 years (highly variable by chart)",
  },
};

/**
 * Look up the interpretation for a planet transiting a house.
 * Returns undefined if no entry exists.
 */
export function getCycleInterpretation(
  planet: string,
  houseNumber: number,
): TransitInterpretation | undefined {
  return DATA[`${planet}:${houseNumber}`];
}
